version: "3.0"
services:
  postgis:
    image: otp-postgres:dev
    build: 
      context: ./init
      dockerfile: Dockerfile
    environment: 
      POSTGRES_PASSWORD: penisz123
    ports:
      - 5432:5432
  pgadmin:
    image: adminer:4.7.4-standalone
    ports:
    - 8080:8080
  dotnet:
    image: otp-dotnet:dev
    build:
      context: ../Backend
      dockerfile: Dockerfile
    ports:
      - 80:80