version: "3.0"
services:
  postgis:
    image: otp-postgres:dev
    build: 
      context: ./init
      dockerfile: Dockerfile
    environment: 
      POSTGRES_PASSWORD: penisz123
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
    - 80:8080